<?php

declare(strict_types=1);

require_once dirname(__DIR__).'/app/bootstrap.php';
if(getenv('V3_RUN_TESTS')!=='1'||app_config('database.database')!=='webalhasan_v3_phase1_test')exit(77);
$repo=new App\V3\KonselingRepository(app_db());$pRepo=new App\V3\PelanggaranRepository(app_db());$kRepo=new App\V3\KatalogRepository(app_db());$service=v3_konseling_service();$pService=v3_pelanggaran_service();$catalogService=v3_katalog_service();
$fails=0;$assert=static function(bool $ok,string $label)use(&$fails){echo ($ok?'[lulus] ':'[gagal] ').$label.PHP_EOL;if(!$ok)$fails++;};$reject=static function(callable $work,string $label,int $status=422)use($assert){try{$work();$assert(false,$label);}catch(App\V3\V3Exception $e){$assert($e->status===$status,$label.' ('.$e->status.')');}};
$user=static fn(string $name):array=>$repo->one('SELECT id FROM users WHERE username=?',[$name])??throw new RuntimeException('Fixture hilang '.$name);
$admin=$user('sbx_admin');$pembimbingA=$user('sbx_pengurus_a');$pembimbingB=$user('sbx_pengurus_b');$murobiA=$user('sbx_murobi_a');$murobiB=$user('sbx_murobi_b');$ortuA=$user('sbx_ortu_a');
$year=(int)$repo->one("SELECT id FROM tahun_ajaran WHERE status='Aktif' AND archived_at IS NULL ORDER BY id LIMIT 1")['id'];$childA=(int)$repo->one("SELECT sw.santri_id FROM santri_wali sw JOIN users u ON u.wali_id=sw.wali_id WHERE u.username='sbx_ortu_a' AND sw.archived_at IS NULL LIMIT 1")['santri_id'];$childB=(int)$repo->one("SELECT sw.santri_id FROM santri_wali sw JOIN users u ON u.wali_id=sw.wali_id WHERE u.username='sbx_ortu_b' AND sw.archived_at IS NULL LIMIT 1")['santri_id'];
$tag='SBX-F3-'.bin2hex(random_bytes(5));$key=static fn(string $prefix):string=>$prefix.'-'.bin2hex(random_bytes(10));$period=['tanggal_mulai'=>date('Y-m-d',time()-86400),'tanggal_selesai'=>'','is_active'=>1];
$categoryId=$catalogService->save('kategori',$period+['kode'=>$tag,'nama'=>'SBX Kategori F3 '.$tag,'uraian'=>'Fixture fiktif'],$admin);$catalogId=$catalogService->save('katalog',$period+['kode'=>$tag,'nama'=>'SBX Jenis F3 '.$tag,'kategori_id'=>$categoryId,'tingkat'=>'Ringan','poin_default'=>3,'uraian'=>'Fixture Fase 3'],$admin);
foreach($kRepo->rows('SELECT * FROM v3_ambang WHERE is_active=1 AND archived_at IS NULL') as $old)$catalogService->save('ambang',array_replace($old,['is_active'=>0,'alasan'=>'Isolasi suite Fase 3']),$admin,(int)$old['id']);
$thresholdId=$catalogService->save('ambang',$period+['tahun_ajaran_id'=>$year,'nilai_minimum'=>0,'nilai_maksimum'=>'','label'=>'SBX tindak lanjut '.$tag,'rekomendasi'=>'Hubungkan manual ke kasus konseling'],$admin);
$base=['santri_id'=>$childA,'tahun_ajaran_id'=>$year,'katalog_id'=>$catalogId,'tempat'=>'SBX area F3'];
$first=$pService->create($pembimbingA,$base+['waktu_kejadian'=>date('Y-m-d\TH:i',time()-7200),'uraian'=>'SBX pelanggaran pertama '.$tag,'idempotency_key'=>$key('violation-a')]);$firstId=(int)$first['data']['pelanggaran']['id'];$recommendationId=(int)($first['data']['rekomendasi_baru'][0]??0);
$second=$pService->create($pembimbingA,$base+['waktu_kejadian'=>date('Y-m-d\TH:i',time()-3600),'uraian'=>'SBX pelanggaran kedua '.$tag,'idempotency_key'=>$key('violation-b')]);$secondId=(int)$second['data']['pelanggaran']['id'];
$assert($recommendationId>0,'Fixture menghasilkan rekomendasi yang masih berlaku');

$caseInput=['santri_id'=>$childA,'tahun_ajaran_id'=>$year,'tujuan'=>'SBX tujuan internal sangat rahasia '.$tag,'kerahasiaan'=>'Rahasia','dibuka_pada'=>date('Y-m-d\TH:i',time()-1800),'pelanggaran_ids'=>[$firstId,$secondId],'rekomendasi_ids'=>[$recommendationId],'idempotency_key'=>$key('case')];
$created=$service->createCase($pembimbingA,$caseInput);$caseId=(int)$created['data']['kasus']['id'];$assert($created['status']===201&&!$created['replayed'],'Pembimbing membuka kasus dalam cakupan');$assert(count($created['data']['tautan_ids'])===2,'Satu kasus menautkan beberapa pelanggaran santri yang sama');$assert((int)$repo->one('SELECT ditindaklanjuti_kasus_id FROM v3_rekomendasi WHERE id=?',[$recommendationId])['ditindaklanjuti_kasus_id']===$caseId,'Rekomendasi berlaku ditautkan manual ke kasus');
$reject(fn()=>$service->addLinks($pembimbingA,$caseId,['pelanggaran_ids'=>[$firstId],'alasan'=>'Duplikat tautan fixture','idempotency_key'=>$key('duplicate-link')]),'Tautan tingkat kasus yang sama tidak dapat digandakan',409);
$replay=$service->createCase($pembimbingA,$caseInput);$assert($replay['replayed']&&(int)$replay['data']['kasus']['id']===$caseId,'Retry kasus me-replay satu dampak bisnis');
$reject(fn()=>$service->createCase($pembimbingA,array_replace($caseInput,['santri_id'=>$childB,'idempotency_key'=>$key('cross-create')])),'Pembimbing tidak membuat kasus di luar cakupan',403);
$reject(fn()=>$service->createCase($pembimbingA,array_replace($caseInput,['pelanggaran_ids'=>[$firstId],'rekomendasi_ids'=>[$recommendationId],'idempotency_key'=>$key('used-rec')])),'Rekomendasi yang sudah ditindaklanjuti tidak dapat ditautkan ulang',409);

$sessionOne=$service->createSession($pembimbingA,$caseId,['jadwal'=>date('Y-m-d\TH:i',time()+3600),'tindak_lanjut'=>'SBX rencana internal satu','pelanggaran_ids'=>[$firstId],'idempotency_key'=>$key('session-a')]);$sessionOneId=(int)$sessionOne['data']['sesi']['id'];
$sessionTwo=$service->createSession($pembimbingA,$caseId,['jadwal'=>date('Y-m-d\TH:i',time()+7200),'tindak_lanjut'=>'SBX rencana internal dua','pelanggaran_ids'=>[$firstId],'idempotency_key'=>$key('session-b')]);$sessionTwoId=(int)$sessionTwo['data']['sesi']['id'];
$assert((int)$repo->one('SELECT COUNT(*) n FROM v3_konseling_sesi WHERE kasus_id=?',[$caseId])['n']===2,'Dua sesi tersimpan sebagai baris berbeda dalam satu kasus');$assert((int)$repo->one('SELECT COUNT(*) n FROM v3_konseling_tautan WHERE pelanggaran_id=? AND kasus_id=?',[$firstId,$caseId])['n']===3,'Satu pelanggaran ditindaklanjuti pada tingkat kasus dan beberapa sesi');
$violationDetail=$pService->show($pembimbingA,$firstId);$sessionIds=array_values(array_filter(array_column($violationDetail['konseling'],'sesi_id')));$assert(in_array($sessionOneId,$sessionIds,true)&&in_array($sessionTwoId,$sessionIds,true),'Detail pelanggaran menampilkan seluruh sesi tindak lanjut tanpa menggandakan pelanggaran');

$completeInput=['version'=>1,'status'=>'Selesai','realisasi'=>date('Y-m-d\TH:i'),'ringkasan_internal'=>'SBX isi konseling rahasia '.$tag,'hasil'=>'SBX hasil internal '.$tag,'tindak_lanjut'=>'SBX tindak lanjut internal '.$tag,'idempotency_key'=>$key('complete')];$completed=$service->transitionSession($pembimbingA,$sessionOneId,$completeInput);$assert($completed['data']['sesi']['status']==='Selesai','Sesi dapat diselesaikan dengan ringkasan dan hasil internal');$assert($service->transitionSession($pembimbingA,$sessionOneId,$completeInput)['replayed'],'Retry transisi sesi terminal me-replay dampak pertama');
$reject(fn()=>$service->transitionSession($pembimbingA,$sessionOneId,['version'=>1,'status'=>'Tidak Hadir','idempotency_key'=>$key('stale-status')]),'Versi lama sesi ditolak tanpa menimpa perubahan baru',409);
$corrected=$service->correctSession($pembimbingA,$sessionOneId,['version'=>2,'jadwal'=>date('Y-m-d\TH:i',time()+3600),'ringkasan_internal'=>'SBX isi dikoreksi '.$tag,'hasil'=>'SBX hasil dikoreksi '.$tag,'tindak_lanjut'=>'SBX tindak lanjut dikoreksi '.$tag,'alasan'=>'Koreksi catatan sesi selesai','idempotency_key'=>$key('correct-session')]);$correctedId=(int)$corrected['data']['sesi']['id'];$assert($correctedId!==$sessionOneId&&(int)$repo->one('SELECT COUNT(*) n FROM v3_konseling_sesi WHERE revisi_dari_id=?',[$sessionOneId])['n']===1,'Koreksi sesi selesai membuat revisi beralasan');$assert((string)$repo->session($sessionOneId)['ringkasan_internal']==='SBX isi konseling rahasia '.$tag,'Koreksi sesi tidak menimpa isi historis');
$reject(fn()=>$service->correctSession($pembimbingA,$sessionOneId,['version'=>2,'alasan'=>'Versi lama kedua','idempotency_key'=>$key('stale-correct')]),'Sumber sesi tidak dapat memiliki revisi kedua',409);

$rescheduled=$service->transitionSession($pembimbingA,$sessionTwoId,['version'=>1,'status'=>'Dijadwalkan Ulang','jadwal'=>date('Y-m-d\TH:i',time()+10800),'realisasi'=>date('Y-m-d\TH:i'),'alasan'=>'Penyesuaian jadwal pembimbing','idempotency_key'=>$key('reschedule')]);$rescheduledId=(int)$rescheduled['data']['sesi']['id'];$assert($rescheduledId!==$sessionTwoId&&$rescheduled['data']['sesi']['status']==='Dijadwalkan Ulang'&&$rescheduled['data']['sesi']['alasan_penjadwalan_ulang']!==null&&$rescheduled['data']['sesi']['realisasi']===null,'Penjadwalan ulang membentuk revisi dengan alasan terpisah tanpa realisasi');
$invalidBefore=(int)$repo->one('SELECT COUNT(*) n FROM v3_konseling_sesi WHERE kasus_id=?',[$caseId])['n'];$reject(fn()=>$service->transitionSession($pembimbingA,$correctedId,['version'=>1,'status'=>'Dibatalkan','alasan'=>'Tidak sah sesudah selesai','idempotency_key'=>$key('invalid-terminal')]),'Transisi dari sesi terminal ditolak',422);$assert((int)$repo->one('SELECT COUNT(*) n FROM v3_konseling_sesi WHERE kasus_id=?',[$caseId])['n']===$invalidBefore,'Transisi tidak sah tidak menulis perubahan parsial');

$murobiDetail=$service->show($murobiA,$caseId);$assert(!$murobiDetail['akses_internal']&&!array_key_exists('tujuan',$murobiDetail['kasus'])&&$murobiDetail['rekomendasi']===[],'Murobi terkait membaca metadata yang diizinkan tanpa tujuan/rekomendasi internal');$murobiSession=$murobiDetail['sesi'][0];$assert(array_intersect(['ringkasan_internal','hasil','tindak_lanjut','alasan_revisi'],array_keys($murobiSession))===[],'Serializer murobi tidak memuat isi sesi internal');
$ack=$service->acknowledge($murobiA,'kasus',$caseId,['catatan'=>'SBX catatan murobi terpisah','idempotency_key'=>$key('ack-case')]);$assert($ack['status']===201&&(int)$repo->one('SELECT COUNT(*) n FROM v3_murobi_catatan WHERE kasus_id=?',[$caseId])['n']===1,'Murobi terkait memberi catatan kasus pada kolom sumber terpisah');$service->acknowledge($murobiA,'sesi',$rescheduledId,['catatan'=>'SBX catatan sesi murobi','idempotency_key'=>$key('ack-session')]);
$reject(fn()=>$service->show($murobiB,$caseId),'Murobi lain ditolak dari detail kasus',403);$reject(fn()=>$service->show($pembimbingB,$caseId),'Pembimbing lain ditolak dari detail kasus',403);$reject(fn()=>$service->show($ortuA,$caseId),'Orang tua ditolak dari endpoint internal kasus',403);$reject(fn()=>$service->acknowledge($murobiB,'kasus',$caseId,['idempotency_key'=>$key('ack-cross')]),'Murobi lain tidak dapat memberi catatan',403);
$assert(count(array_filter($service->page($pembimbingB,[])['rows'],static fn(array $row):bool=>(int)$row['id']===$caseId))===0,'Daftar pembimbing lain tidak membocorkan kasus');$assert(count(array_filter($service->page($murobiA,[])['rows'],static fn(array $row):bool=>(int)$row['id']===$caseId))===1,'Murobi terkait melihat kasus pada daftar cakupannya');
$public=$service->parentSerializer(['id'=>99,'santri_id'=>$childA,'ringkasan'=>'Ringkasan publik eksplisit','tindak_lanjut'=>'Tindak lanjut publik','diterbitkan_pada'=>date('Y-m-d H:i:s'),'tujuan'=>'RAHASIA','ringkasan_internal'=>'RAHASIA','hasil'=>'RAHASIA','catatan_murobi'=>'RAHASIA','pembimbing_id'=>999]);$assert(array_keys($public)===['id','santri_id','ringkasan','tindak_lanjut','diterbitkan_pada','ditarik_pada','dibaca_pada']&&strpos(json_encode($public),'RAHASIA')===false,'DTO orang tua allowlist tidak pernah membawa field internal');

$adminReadBefore=(int)$repo->one("SELECT COUNT(*) n FROM audit_logs WHERE action='v3.konseling.kasus.dilihat.admin' AND entity_id=?",[$caseId])['n'];$adminDetail=$service->show($admin,$caseId);$adminReadAfter=(int)$repo->one("SELECT COUNT(*) n FROM audit_logs WHERE action='v3.konseling.kasus.dilihat.admin' AND entity_id=?",[$caseId])['n'];$assert($adminDetail['akses_internal']&&$adminReadAfter===$adminReadBefore+1,'Pembukaan detail sensitif oleh admin tercatat sebagai audit akses');
$adminCase=$service->correctCase($admin,$caseId,['version'=>(int)$repo->case($caseId)['version'],'tujuan'=>'SBX tujuan terkoreksi admin '.$tag,'kerahasiaan'=>'Internal','alasan'=>'Koreksi administratif beralasan','idempotency_key'=>$key('admin-case')]);$assert($adminCase['data']['kasus']['tujuan']==='SBX tujuan terkoreksi admin '.$tag,'Admin mengoreksi kasus hanya melalui alasan wajib');$auditAction=(string)$repo->one("SELECT action FROM audit_logs WHERE entity_type='v3_konseling_kasus' AND entity_id=? ORDER BY id DESC LIMIT 1",[$caseId])['action'];$assert($auditAction==='v3.konseling.kasus.dikoreksi.admin','Audit membedakan koreksi administratif');
$caseVersion=(int)$repo->case($caseId)['version'];$reject(fn()=>$service->transitionCase($pembimbingA,$caseId,['version'=>$caseVersion,'status'=>'Dalam Pendampingan','idempotency_key'=>$key('invalid-case')]),'Transisi status kasus yang tidak sah ditolak',422);$assert((int)$repo->case($caseId)['version']===$caseVersion,'Transisi kasus tidak sah tidak mengubah versi');
$closeInput=['version'=>$caseVersion,'status'=>'Selesai','ringkasan_penutupan'=>'SBX ringkasan hasil penutupan '.$tag,'idempotency_key'=>$key('close')];$closed=$service->transitionCase($pembimbingA,$caseId,$closeInput);$assert($closed['data']['kasus']['status']==='Selesai'&&$closed['data']['kasus']['ditutup_pada']!==null,'Kasus ditutup hanya dengan ringkasan hasil');$assert($service->transitionCase($pembimbingA,$caseId,$closeInput)['replayed'],'Retry penutupan kasus me-replay dampak pertama');$assert((int)$repo->one('SELECT COUNT(*) n FROM v3_konseling_sesi WHERE kasus_id=?',[$caseId])['n']===$invalidBefore,'Penutupan mempertahankan seluruh sesi dan revisi');$assert((int)$repo->one('SELECT COUNT(*) n FROM v3_konseling_tautan WHERE kasus_id=?',[$caseId])['n']===4,'Penutupan mempertahankan seluruh tautan pelanggaran');

$businessBefore=(int)$repo->one('SELECT COUNT(*) n FROM v3_konseling_kasus')['n'];$outboxBefore=(int)$repo->one("SELECT COUNT(*) n FROM notifikasi_outbox WHERE event_type LIKE 'v3_konseling%'")['n'];$repo->execute("CREATE TRIGGER v3_f3_audit_failure BEFORE INSERT ON audit_logs FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Synthetic audit failure'");
try{$reject(fn()=>$service->createCase($pembimbingA,['santri_id'=>$childA,'tahun_ajaran_id'=>$year,'tujuan'=>'SBX transaksi gagal '.$tag,'kerahasiaan'=>'Rahasia','dibuka_pada'=>date('Y-m-d\TH:i'),'idempotency_key'=>$key('audit-fail')]),'Kegagalan audit menggulung kasus dan outbox',503);}finally{$repo->execute('DROP TRIGGER v3_f3_audit_failure');}
$assert((int)$repo->one('SELECT COUNT(*) n FROM v3_konseling_kasus')['n']===$businessBefore&&(int)$repo->one("SELECT COUNT(*) n FROM notifikasi_outbox WHERE event_type LIKE 'v3_konseling%'")['n']===$outboxBefore,'Tidak ada kasus atau outbox parsial setelah audit gagal');
$outbox=$repo->all("SELECT judul,isi,data_json FROM notifikasi_outbox WHERE event_type LIKE 'v3_konseling%'");$safe=true;foreach($outbox as $notification){$payload=implode(' ',array_map('strval',$notification));if(str_contains($payload,$tag)||preg_match('/tujuan|ringkasan_internal|hasil|tindak_lanjut|catatan/',$payload))$safe=false;}$assert($outbox!==[]&&$safe,'Outbox konseling hanya memuat pesan generik tanpa rincian sensitif');
exit($fails?1:0);
