-- PRD V3 Fase 1: tambahan saja, tanpa backfill data ambigu.

CREATE TABLE IF NOT EXISTS v3_kategori (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    kode VARCHAR(40) NOT NULL UNIQUE,
    nama VARCHAR(150) NOT NULL,
    uraian TEXT NULL,
    tanggal_mulai DATE NOT NULL,
    tanggal_selesai DATE NULL,
    is_active TINYINT NOT NULL DEFAULT 1,
    alasan_status VARCHAR(1000) NULL,
    CHECK (is_active IN (0,1)),
    CHECK (tanggal_selesai IS NULL OR tanggal_selesai >= tanggal_mulai),
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    archived_at DATETIME NULL,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id),
    CHECK (version > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS v3_katalog (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    kode VARCHAR(40) NOT NULL UNIQUE,
    nama VARCHAR(150) NOT NULL,
    kategori_id BIGINT UNSIGNED NOT NULL,
    tingkat ENUM('Ringan','Sedang','Berat') NOT NULL,
    poin_default INT NOT NULL,
    uraian TEXT NULL,
    FOREIGN KEY (kategori_id) REFERENCES v3_kategori(id),
    CHECK (poin_default >= 0),
    INDEX katalog_filter (is_active, tingkat, tanggal_mulai, tanggal_selesai),
    tanggal_mulai DATE NOT NULL,
    tanggal_selesai DATE NULL,
    is_active TINYINT NOT NULL DEFAULT 1,
    alasan_status VARCHAR(1000) NULL,
    CHECK (is_active IN (0,1)),
    CHECK (tanggal_selesai IS NULL OR tanggal_selesai >= tanggal_mulai),
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    archived_at DATETIME NULL,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id),
    CHECK (version > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS v3_ambang (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    tahun_ajaran_id INT NOT NULL,
    nilai_minimum INT NOT NULL,
    nilai_maksimum INT NULL,
    label VARCHAR(150) NOT NULL,
    rekomendasi TEXT NOT NULL,
    FOREIGN KEY (tahun_ajaran_id) REFERENCES tahun_ajaran(id),
    CHECK (nilai_minimum >= 0),
    CHECK (nilai_maksimum IS NULL OR nilai_maksimum >= nilai_minimum),
    INDEX ambang_rentang (tahun_ajaran_id, is_active, nilai_minimum, nilai_maksimum),
    tanggal_mulai DATE NOT NULL,
    tanggal_selesai DATE NULL,
    is_active TINYINT NOT NULL DEFAULT 1,
    alasan_status VARCHAR(1000) NULL,
    CHECK (is_active IN (0,1)),
    CHECK (tanggal_selesai IS NULL OR tanggal_selesai >= tanggal_mulai),
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    archived_at DATETIME NULL,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id),
    CHECK (version > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS v3_pelanggaran (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    santri_id INT NOT NULL,
    tahun_ajaran_id INT NOT NULL,
    pembimbing_id BIGINT UNSIGNED NULL,
    pembimbing_assignment_id BIGINT UNSIGNED NULL,
    katalog_id BIGINT UNSIGNED NULL,
    waktu_kejadian DATETIME NOT NULL,
    tempat VARCHAR(255) NULL,
    uraian TEXT NOT NULL,
    saksi TEXT NULL,
    kategori_snapshot VARCHAR(150) NOT NULL,
    tingkat_snapshot VARCHAR(20) NOT NULL,
    poin_snapshot INT NOT NULL,
    cakupan_snapshot LONGTEXT NULL,
    status ENUM('Draf','Dicatat','Ditindaklanjuti','Selesai','Dibatalkan') NOT NULL DEFAULT 'Draf',
    data_warisan TINYINT NOT NULL DEFAULT 0,
    sumber_warisan VARCHAR(100) NULL,
    id_warisan VARCHAR(100) NULL,
    fingerprint CHAR(64) NULL,
    idempotency_key VARCHAR(100) NULL,
    revisi_dari_id BIGINT UNSIGNED NULL,
    alasan_revisi TEXT NULL,
    FOREIGN KEY (santri_id) REFERENCES santri(id),
    FOREIGN KEY (tahun_ajaran_id) REFERENCES tahun_ajaran(id),
    FOREIGN KEY (pembimbing_id) REFERENCES pengurus(id),
    FOREIGN KEY (pembimbing_assignment_id) REFERENCES pembimbing_assignments(id),
    FOREIGN KEY (katalog_id) REFERENCES v3_katalog(id),
    FOREIGN KEY (revisi_dari_id) REFERENCES v3_pelanggaran(id),
    UNIQUE KEY pelanggaran_warisan (sumber_warisan,id_warisan),
    UNIQUE KEY pelanggaran_retry (created_by,idempotency_key),
    UNIQUE KEY pelanggaran_fingerprint (santri_id,tahun_ajaran_id,fingerprint),
    INDEX pelanggaran_riwayat (santri_id,tahun_ajaran_id,waktu_kejadian),
    CHECK (poin_snapshot >= 0),
    CHECK (data_warisan IN (0,1)),
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    archived_at DATETIME NULL,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id),
    CHECK (version > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS v3_poin_ledger (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    pelanggaran_id BIGINT UNSIGNED NOT NULL,
    santri_id INT NOT NULL,
    tahun_ajaran_id INT NOT NULL,
    perubahan_poin INT NOT NULL,
    alasan TEXT NOT NULL,
    event_key VARCHAR(150) NOT NULL UNIQUE,
    pembalik_dari_id BIGINT UNSIGNED NULL UNIQUE,
    FOREIGN KEY (pelanggaran_id) REFERENCES v3_pelanggaran(id),
    FOREIGN KEY (santri_id) REFERENCES santri(id),
    FOREIGN KEY (tahun_ajaran_id) REFERENCES tahun_ajaran(id),
    FOREIGN KEY (pembalik_dari_id) REFERENCES v3_poin_ledger(id),
    INDEX ledger_rekonsiliasi (santri_id,tahun_ajaran_id),
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    archived_at DATETIME NULL,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id),
    CHECK (version > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS v3_konseling_kasus (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    santri_id INT NOT NULL,
    tahun_ajaran_id INT NOT NULL,
    pembimbing_id BIGINT UNSIGNED NULL,
    pembimbing_assignment_id BIGINT UNSIGNED NULL,
    tujuan TEXT NOT NULL,
    kerahasiaan ENUM('Internal','Rahasia') NOT NULL DEFAULT 'Rahasia',
    status ENUM('Dibuka','Dalam Pendampingan','Selesai','Dibatalkan') NOT NULL DEFAULT 'Dibuka',
    dibuka_pada DATETIME NOT NULL,
    ditutup_pada DATETIME NULL,
    ringkasan_penutupan TEXT NULL,
    cakupan_snapshot LONGTEXT NULL,
    data_warisan TINYINT NOT NULL DEFAULT 0,
    sumber_warisan VARCHAR(100) NULL,
    id_warisan VARCHAR(100) NULL,
    idempotency_key VARCHAR(100) NULL,
    FOREIGN KEY (santri_id) REFERENCES santri(id),
    FOREIGN KEY (tahun_ajaran_id) REFERENCES tahun_ajaran(id),
    FOREIGN KEY (pembimbing_id) REFERENCES pengurus(id),
    FOREIGN KEY (pembimbing_assignment_id) REFERENCES pembimbing_assignments(id),
    UNIQUE KEY kasus_retry (created_by,idempotency_key),
    UNIQUE KEY kasus_warisan (sumber_warisan,id_warisan),
    INDEX kasus_riwayat (santri_id,tahun_ajaran_id,status),
    CHECK (data_warisan IN (0,1)),
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    archived_at DATETIME NULL,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id),
    CHECK (version > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS v3_konseling_sesi (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    kasus_id BIGINT UNSIGNED NOT NULL,
    pembimbing_id BIGINT UNSIGNED NOT NULL,
    jadwal DATETIME NOT NULL,
    realisasi DATETIME NULL,
    status ENUM('Dijadwalkan','Selesai','Tidak Hadir','Dijadwalkan Ulang','Dibatalkan') NOT NULL DEFAULT 'Dijadwalkan',
    ringkasan_internal TEXT NULL,
    hasil TEXT NULL,
    tindak_lanjut TEXT NULL,
    jadwal_berikut DATETIME NULL,
    revisi_dari_id BIGINT UNSIGNED NULL,
    alasan_revisi TEXT NULL,
    idempotency_key VARCHAR(100) NULL,
    FOREIGN KEY (kasus_id) REFERENCES v3_konseling_kasus(id),
    FOREIGN KEY (pembimbing_id) REFERENCES pengurus(id),
    FOREIGN KEY (revisi_dari_id) REFERENCES v3_konseling_sesi(id),
    UNIQUE KEY sesi_retry (created_by,idempotency_key),
    INDEX sesi_jadwal (kasus_id,jadwal),
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    archived_at DATETIME NULL,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id),
    CHECK (version > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS v3_konseling_tautan (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    pelanggaran_id BIGINT UNSIGNED NOT NULL,
    kasus_id BIGINT UNSIGNED NOT NULL,
    sesi_id BIGINT UNSIGNED NULL,
    sesi_key BIGINT UNSIGNED GENERATED ALWAYS AS (COALESCE(sesi_id,0)) STORED,
    is_active TINYINT NOT NULL DEFAULT 1,
    alasan TEXT NULL,
    FOREIGN KEY (pelanggaran_id) REFERENCES v3_pelanggaran(id),
    FOREIGN KEY (kasus_id) REFERENCES v3_konseling_kasus(id),
    FOREIGN KEY (sesi_id) REFERENCES v3_konseling_sesi(id),
    UNIQUE KEY tautan_unik (pelanggaran_id,kasus_id,sesi_key),
    CHECK (is_active IN (0,1)),
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    archived_at DATETIME NULL,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id),
    CHECK (version > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS v3_murobi_catatan (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    pelanggaran_id BIGINT UNSIGNED NULL,
    kasus_id BIGINT UNSIGNED NULL,
    sesi_id BIGINT UNSIGNED NULL,
    sumber_version INT UNSIGNED NOT NULL,
    FOREIGN KEY (pelanggaran_id) REFERENCES v3_pelanggaran(id),
    FOREIGN KEY (kasus_id) REFERENCES v3_konseling_kasus(id),
    FOREIGN KEY (sesi_id) REFERENCES v3_konseling_sesi(id),
    CHECK ((pelanggaran_id IS NOT NULL) + (kasus_id IS NOT NULL) + (sesi_id IS NOT NULL) = 1),
    CHECK (sumber_version > 0),
    guru_id INT NOT NULL,
    murobi_assignment_id BIGINT UNSIGNED NOT NULL,
    dilihat_pada DATETIME NULL,
    diketahui_pada DATETIME NULL,
    catatan TEXT NULL,
    event_key VARCHAR(150) NOT NULL UNIQUE,
    FOREIGN KEY (guru_id) REFERENCES guru(id),
    FOREIGN KEY (murobi_assignment_id) REFERENCES murobi_assignments(id),
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    archived_at DATETIME NULL,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id),
    CHECK (version > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS v3_publikasi (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    pelanggaran_id BIGINT UNSIGNED NULL,
    kasus_id BIGINT UNSIGNED NULL,
    sesi_id BIGINT UNSIGNED NULL,
    sumber_version INT UNSIGNED NOT NULL,
    FOREIGN KEY (pelanggaran_id) REFERENCES v3_pelanggaran(id),
    FOREIGN KEY (kasus_id) REFERENCES v3_konseling_kasus(id),
    FOREIGN KEY (sesi_id) REFERENCES v3_konseling_sesi(id),
    CHECK ((pelanggaran_id IS NOT NULL) + (kasus_id IS NOT NULL) + (sesi_id IS NOT NULL) = 1),
    CHECK (sumber_version > 0),
    santri_id INT NOT NULL,
    wali_id BIGINT UNSIGNED NOT NULL,
    ringkasan TEXT NOT NULL,
    tindak_lanjut TEXT NULL,
    diterbitkan_pada DATETIME NOT NULL,
    ditarik_pada DATETIME NULL,
    alasan_penarikan TEXT NULL,
    alasan_penerima TEXT NULL,
    dibaca_pada DATETIME NULL,
    event_key VARCHAR(150) NOT NULL UNIQUE,
    FOREIGN KEY (santri_id) REFERENCES santri(id),
    FOREIGN KEY (wali_id) REFERENCES wali(id),
    INDEX publikasi_penerima (wali_id,santri_id,diterbitkan_pada),
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    archived_at DATETIME NULL,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id),
    CHECK (version > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS v3_lampiran (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    pelanggaran_id BIGINT UNSIGNED NULL,
    kasus_id BIGINT UNSIGNED NULL,
    sesi_id BIGINT UNSIGNED NULL,
    sumber_version INT UNSIGNED NOT NULL,
    FOREIGN KEY (pelanggaran_id) REFERENCES v3_pelanggaran(id),
    FOREIGN KEY (kasus_id) REFERENCES v3_konseling_kasus(id),
    FOREIGN KEY (sesi_id) REFERENCES v3_konseling_sesi(id),
    CHECK ((pelanggaran_id IS NOT NULL) + (kasus_id IS NOT NULL) + (sesi_id IS NOT NULL) = 1),
    CHECK (sumber_version > 0),
    nama_aman VARCHAR(255) NOT NULL,
    mime VARCHAR(100) NOT NULL,
    ukuran BIGINT NOT NULL,
    sha256 CHAR(64) NOT NULL,
    lokasi_privat VARCHAR(500) NOT NULL,
    CHECK (ukuran > 0),
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    archived_at DATETIME NULL,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id),
    CHECK (version > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS v3_idempotency (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    operation VARCHAR(100) NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    response_json LONGTEXT NULL,
    status_code INT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id),
    UNIQUE KEY v3_request_unik (user_id,operation,idempotency_key),
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    archived_at DATETIME NULL,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id),
    CHECK (version > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
