<?php

declare(strict_types=1);

use App\MasterData\MasterDataException;
require_once __DIR__ . '/_guard.php';
require_once __DIR__ . '/_master_ui.php';
$service=master_data_service();
if($_SERVER['REQUEST_METHOD']==='POST'){try{$action=(string)($_POST['action']??'');if($action==='save'){$service->saveMurobi($_POST,(int)$currentUser['id']);master_flash('success','Penugasan murobi berhasil disimpan tanpa memberikan hak approval izin.');}else{$service->setMurobiState((int)($_POST['id']??0),$action);master_flash('success','Status penugasan murobi diperbarui.');}}catch(MasterDataException $e){master_flash('danger',$e->getMessage());}master_redirect('admin_murobi.php');}
$rows=$service->murobi();$gurus=$service->guruOptions();$years=$service->years();$classes=$service->classes();$rooms=$service->kamarOptions();master_header('Penugasan Murobi');
?>
<div class="border-bottom pb-3 mb-4"><h1 class="h3">Penugasan Murobi</h1><p class="text-muted mb-0">Penugasan terkait semester dan kelompok binaan; tidak memberi akun atau akses approval izin.</p></div>
<div class="card border-0 shadow-sm mb-4"><div class="card-header bg-white"><strong>Tambah Penugasan</strong></div><div class="card-body"><form method="post" class="row g-3"><?= master_csrf() ?><input type="hidden" name="action" value="save"><div class="col-md-4"><label class="form-label">Guru</label><select class="form-select" name="guru_id" required><option value="">Pilih guru</option><?php foreach($gurus as $g): ?><option value="<?= (int)$g['id'] ?>"><?= master_e($g['nama_guru']) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Tahun ajaran</label><select class="form-select" name="tahun_ajaran_id" required><?php foreach($years as $year):if($year['archived_at'])continue; ?><option value="<?= (int)$year['id'] ?>"><?= master_e($year['tahun'].' '.$year['semester'].($year['status']==='Aktif'?' — Aktif':'')) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><label class="form-label">Jenis kelompok</label><select class="form-select" name="target_type" id="target_type"><option>Kamar</option><option>Kelas</option></select></div><div class="col-md-3 target-kamar"><label class="form-label">Kamar</label><select class="form-select" name="kamar_id"><option value="">Pilih kamar</option><?php foreach($rooms as $room): ?><option value="<?= (int)$room['id'] ?>"><?= master_e($room['nama_kamar']) ?></option><?php endforeach; ?></select></div><div class="col-md-3 target-kelas d-none"><label class="form-label">Kelas</label><select class="form-select" name="kelas_id"><option value="">Pilih kelas</option><?php foreach($classes as $class):if($class['archived_at'])continue; ?><option value="<?= (int)$class['id'] ?>"><?= master_e($class['nama_kelas']) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Tanggal mulai</label><input class="form-control" type="date" name="tanggal_mulai" value="<?= date('Y-m-d') ?>" required></div><div class="col-md-3"><label class="form-label">Tanggal selesai (opsional)</label><input class="form-control" type="date" name="tanggal_selesai"></div><div class="col-md-3 d-flex align-items-end"><button class="btn btn-success">Simpan Penugasan</button></div></form></div></div>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Guru</th><th>Semester</th><th>Kelompok</th><th>Rentang</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?= master_e($r['nama_guru']) ?></td><td><?= master_e($r['tahun'].' '.$r['semester']) ?></td><td><?= master_e($r['target_type'].': '.$r['target_name']) ?></td><td><?= master_e($r['tanggal_mulai'].' — '.($r['tanggal_selesai']?:'seterusnya')) ?></td><td><?= $r['archived_at']?'Arsip':((int)$r['is_active']===1?'Aktif':'Nonaktif') ?></td><td><div class="d-flex gap-1"><form method="post"><?= master_csrf() ?><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><button class="btn btn-sm btn-outline-secondary" name="action" value="<?= (int)$r['is_active']===1?'deactivate':'activate' ?>"><?= (int)$r['is_active']===1?'Nonaktifkan':'Aktifkan' ?></button></form><form method="post"><?= master_csrf() ?><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><button class="btn btn-sm btn-outline-danger" name="action" value="<?= $r['archived_at']?'restore':'archive' ?>"><?= $r['archived_at']?'Pulihkan':'Arsipkan' ?></button></form></div></td></tr><?php endforeach; ?><?php if(!$rows): ?><tr><td colspan="6" class="text-muted text-center py-4">Belum ada penugasan murobi.</td></tr><?php endif; ?></tbody></table></div></div>
<script>document.addEventListener('DOMContentLoaded',()=>{const type=document.getElementById('target_type');const sync=()=>{document.querySelector('.target-kamar').classList.toggle('d-none',type.value!=='Kamar');document.querySelector('.target-kelas').classList.toggle('d-none',type.value!=='Kelas');};type.addEventListener('change',sync);sync();});</script>
<?php master_footer(); ?>

