<?php

declare(strict_types=1);

use App\MasterData\MasterDataException;
require_once __DIR__ . '/_guard.php';
require_once __DIR__ . '/_master_ui.php';
$service=master_data_service();
if($_SERVER['REQUEST_METHOD']==='POST'){try{$action=(string)($_POST['action']??'');$id=(int)($_POST['id']??0);if($action==='save'){$service->savePengurus($_POST,$id?:null);master_flash('success','Data pengurus berhasil disimpan. Pengurus tidak dibuatkan akun login.');}else{$service->setPengurusState($id,$action);master_flash('success','Status pengurus berhasil diperbarui.');}}catch(MasterDataException $e){master_flash('danger',$e->getMessage());if($action==='save'){ah_validation_keep($_POST,['nama', 'nomor_identitas', 'no_hp', 'jabatan'],$e,'_pengurus_old');master_redirect('admin_pengurus.php?action='.($id?'edit&id='.$id:'create'));}}master_redirect('admin_pengurus.php');}
$page=max(1,(int)($_GET['page']??1));$filters=['q'=>$_GET['q']??'','state'=>$_GET['state']??'active'];$result=$service->pengurusList($filters,$page);$selected=isset($_GET['id'])?$service->pengurus((int)$_GET['id']):null;$mode=(string)($_GET['action']??'');master_header('Master Data Pengurus', ['show_heading' => false]);
?>
<div class="ah-page-head"><div><h1 class="h3">Master Data Pengurus</h1><p class="text-muted mb-0">Akun pengurus dikelola terpisah melalui Akun &amp; Hak Akses.</p></div><a class="btn btn-success align-self-center" href="?action=create">Tambah Pengurus</a></div>
<?php if($mode==='create'||($mode==='edit'&&$selected)):$r=array_replace($selected??[], $_SESSION['_pengurus_old']??[]); ?><div class="card border-0 shadow-sm mb-4"><div class="card-body"><form method="post" class="row g-3"><?= master_csrf() ?><input type="hidden" name="action" value="save"><?php if($selected): ?><input type="hidden" name="id" value="<?= (int)$selected['id'] ?>"><?php endif; ?><div class="col-md-4"><label class="form-label" for="nama">Nama</label><input class="form-control" id="nama" name="nama" required value="<?= master_e($r['nama']??'') ?>"><?= ah_field_error('nama','_pengurus_old') ?></div><div class="col-md-3"><label class="form-label" for="nomor_identitas">Nomor identitas</label><input class="form-control" id="nomor_identitas" name="nomor_identitas" value="<?= master_e($r['nomor_identitas']??'') ?>"><?= ah_field_error('nomor_identitas','_pengurus_old') ?></div><div class="col-md-2"><label class="form-label" for="no_hp">Nomor HP</label><input class="form-control" id="no_hp" name="no_hp" value="<?= master_e($r['no_hp']??'') ?>"><?= ah_field_error('no_hp','_pengurus_old') ?></div><div class="col-md-3"><label class="form-label" for="jabatan">Jabatan</label><input class="form-control" id="jabatan" name="jabatan" required value="<?= master_e($r['jabatan']??'') ?>"><?= ah_field_error('jabatan','_pengurus_old') ?></div><div><button class="btn btn-success">Simpan</button> <a class="btn btn-light" href="admin_pengurus.php">Batal</a></div></form></div></div><?php endif; ?>
<?php if($mode==='detail'&&$selected): ?><div class="card border-0 shadow-sm mb-4"><div class="card-header bg-white d-flex justify-content-between"><strong>Detail Pengurus #<?= (int)$selected['id'] ?></strong><a href="?action=edit&amp;id=<?= (int)$selected['id'] ?>">Ubah</a></div><div class="card-body row g-3"><div class="col-md-4"><small class="text-muted d-block">Nama</small><?= master_e($selected['nama']) ?></div><div class="col-md-3"><small class="text-muted d-block">Identitas</small><?= master_e($selected['nomor_identitas']?:'-') ?></div><div class="col-md-2"><small class="text-muted d-block">Nomor HP</small><?= master_e($selected['no_hp']?:'-') ?></div><div class="col-md-3"><small class="text-muted d-block">Jabatan</small><?= master_e($selected['jabatan']) ?></div></div></div><?php endif; ?>
<form method="get" class="card card-body border-0 shadow-sm mb-3"><div class="row g-2"><div class="col-md-6"><label class="form-label" for="q">Pencarian pengurus</label><input class="form-control" id="q" name="q" value="<?= master_e($filters['q']) ?>" placeholder="Cari nama, identitas, jabatan, atau HP"></div><div class="col-md-3"><label class="form-label" for="state">Status pengurus</label><select class="form-select" id="state" name="state"><?php foreach(['active'=>'Aktif','inactive'=>'Nonaktif','archived'=>'Arsip','all'=>'Semua'] as $v=>$l): ?><option value="<?= $v ?>" <?= $filters['state']===$v?'selected':'' ?>><?= $l ?></option><?php endforeach; ?></select></div><div class="col-md-3"><button class="btn btn-primary">Terapkan</button></div></div></form>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th scope="col">ID</th><th scope="col">Nama</th><th scope="col">Identitas</th><th scope="col">HP</th><th scope="col">Jabatan</th><th scope="col">Status</th><th scope="col">Aksi</th></tr></thead><tbody><?php foreach($result['rows'] as $r): ?><tr><td><?= (int)$r['id'] ?></td><td><?= master_e($r['nama']) ?></td><td><?= master_e($r['nomor_identitas']?:'-') ?></td><td><?= master_e($r['no_hp']?:'-') ?></td><td><?= master_e($r['jabatan']) ?></td><td><?= $r['archived_at']?'Arsip':((int)$r['is_active']===1?'Aktif':'Nonaktif') ?></td><td><div class="d-flex gap-1"><a class="btn btn-sm btn-outline-primary" href="?action=detail&amp;id=<?= (int)$r['id'] ?>">Detail</a><a class="btn btn-sm btn-outline-warning" href="?action=edit&amp;id=<?= (int)$r['id'] ?>">Ubah</a><form data-confirm="Ubah status pengurus ini? Status aktif memengaruhi kelayakan penugasan pembimbing; akun dan riwayat lama tidak dihapus." method="post"><?= master_csrf() ?><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><button class="btn btn-sm btn-outline-secondary" name="action" value="<?= (int)$r['is_active']===1?'deactivate':'activate' ?>"><?= (int)$r['is_active']===1?'Nonaktifkan':'Aktifkan' ?></button></form><form data-confirm="Ubah status pengurus ini? Status aktif memengaruhi kelayakan penugasan pembimbing; akun dan riwayat lama tidak dihapus." method="post"><?= master_csrf() ?><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><button class="btn btn-sm btn-outline-danger" name="action" value="<?= $r['archived_at']?'restore':'archive' ?>"><?= $r['archived_at']?'Pulihkan':'Arsipkan' ?></button></form></div></td></tr><?php endforeach; ?><?php if ($result['rows'] === []): ?><tr><td colspan="7"><?= ah_empty('Tidak ada pengurus sesuai filter', 'Ubah pencarian/status atau tambahkan pengurus.') ?></td></tr><?php endif; ?></tbody></table></div></div>
<?php master_pagination((int)$result['total'],$page,20);ah_old_clear('_pengurus_old');master_footer(); ?>
