<?php

declare(strict_types=1);

use App\MasterData\MasterDataException;
require_once __DIR__ . '/_guard.php';
require_once __DIR__ . '/_master_ui.php';
$service=master_data_service();
if($_SERVER['REQUEST_METHOD']==='POST'){try{$action=(string)($_POST['action']??'');$id=(int)($_POST['id']??0);if($action==='save'){$service->saveClass($_POST,$id?:null);master_flash('success','Kelas berhasil disimpan.');}elseif($action==='assign'){$service->assignActiveClass($_POST,(int)$currentUser['id']);master_flash('success','Santri ditempatkan ke kelas pada semester aktif; riwayat lama tetap tersimpan.');}else{$service->setClassState($id,$action);master_flash('success','Status kelas berhasil diperbarui.');}}catch(MasterDataException $e){master_flash('danger',$e->getMessage());}master_redirect('admin_kelas.php');}
$rows=$service->classes();$selected=isset($_GET['id'])?$service->class((int)$_GET['id']):null;$mode=(string)($_GET['action']??'');$activeYear=null;foreach($service->years() as $year){if($year['status']==='Aktif'&&!$year['archived_at']){$activeYear=$year;break;}}master_header('Kelas dan Keanggotaan');
?>
<div class="d-flex justify-content-between border-bottom pb-3 mb-4"><div><h1 class="h3">Kelas dan Keanggotaan</h1><p class="text-muted mb-0">Semester aktif: <?= $activeYear?master_e($activeYear['tahun'].' '.$activeYear['semester']):'belum diatur' ?>.</p></div><a class="btn btn-success align-self-center" href="?action=create">Tambah Kelas</a></div>
<?php if($mode==='create'||($mode==='edit'&&$selected)):$r=$selected??[]; ?><div class="card border-0 shadow-sm mb-4"><div class="card-header bg-white"><strong><?= $selected?'Ubah Kelas':'Tambah Kelas' ?></strong></div><div class="card-body"><form method="post" class="row g-3"><?= master_csrf() ?><input type="hidden" name="action" value="save"><?php if($selected): ?><input type="hidden" name="id" value="<?= (int)$selected['id'] ?>"><?php endif; ?><div class="col-md-5"><label class="form-label">Nama kelas</label><input class="form-control" name="nama_kelas" required value="<?= master_e($r['nama_kelas']??'') ?>"></div><div class="col-md-5"><label class="form-label">Jenjang</label><input class="form-control" name="jenjang" required value="<?= master_e($r['jenjang']??'') ?>"></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-success">Simpan</button></div></form></div></div><?php endif; ?>
<div class="card border-0 shadow-sm mb-4"><div class="card-header bg-white"><strong>Tempatkan Santri pada Semester Aktif</strong></div><div class="card-body"><?php if($activeYear): ?><form method="post" class="row g-3"><?= master_csrf() ?><input type="hidden" name="action" value="assign"><div class="col-md-5"><label class="form-label">Santri</label><select class="form-select" name="santri_id" required><option value="">Pilih santri</option><?php foreach($service->santriOptions() as $s): ?><option value="<?= (int)$s['id'] ?>"><?= master_e($s['nis'].' — '.$s['nama_santri']) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Kelas</label><select class="form-select" name="kelas_id" required><?php foreach($rows as $r):if($r['archived_at']||(int)$r['is_active']!==1)continue; ?><option value="<?= (int)$r['id'] ?>"><?= master_e($r['nama_kelas']) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><label class="form-label">Tanggal mulai</label><input class="form-control" type="date" name="tanggal_mulai" value="<?= date('Y-m-d') ?>" required></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary">Tempatkan</button></div></form><?php else: ?><div class="alert alert-warning mb-0">Aktifkan satu tahun ajaran terlebih dahulu.</div><?php endif; ?></div></div>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>ID</th><th>Nama kelas</th><th>Jenjang</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?= (int)$r['id'] ?></td><td><?= master_e($r['nama_kelas']) ?></td><td><?= master_e($r['jenjang']) ?></td><td><?= $r['archived_at']?'Arsip':((int)$r['is_active']===1?'Aktif':'Nonaktif') ?></td><td><div class="d-flex gap-1"><a class="btn btn-sm btn-outline-warning" href="?action=edit&amp;id=<?= (int)$r['id'] ?>">Ubah</a><form method="post"><?= master_csrf() ?><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><button class="btn btn-sm btn-outline-secondary" name="action" value="<?= (int)$r['is_active']===1?'deactivate':'activate' ?>"><?= (int)$r['is_active']===1?'Nonaktifkan':'Aktifkan' ?></button></form><form method="post"><?= master_csrf() ?><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><button class="btn btn-sm btn-outline-danger" name="action" value="<?= $r['archived_at']?'restore':'archive' ?>"><?= $r['archived_at']?'Pulihkan':'Arsipkan' ?></button></form></div></td></tr><?php endforeach; ?></tbody></table></div></div>
<?php master_footer(); ?>
