<?php

declare(strict_types=1);

use App\MasterData\MasterDataException;
require_once __DIR__ . '/_guard.php';
require_once __DIR__ . '/_master_ui.php';
$service=master_data_service();
if($_SERVER['REQUEST_METHOD']==='POST'){try{$action=(string)($_POST['action']??'');$id=(int)($_POST['id']??0);if($action==='save'){$service->saveYear($_POST,$id?:null);master_flash('success','Tahun ajaran berhasil disimpan.');}elseif($action==='activate'){$service->activateYear($id);master_flash('success','Semester aktif berhasil diganti. Tepat satu semester kini aktif.');}elseif($action==='archive'){$service->archiveYear($id);master_flash('success','Tahun ajaran nonaktif berhasil diarsipkan.');}elseif($action==='restore'){$service->restoreYear($id);master_flash('success','Tahun ajaran berhasil dipulihkan.');}}catch(MasterDataException $e){master_flash('danger',$e->getMessage());if($action==='save'){ah_validation_keep($_POST,['tahun', 'semester'],$e,'_tahun_old');master_redirect('admin_tahun.php?action='.($id?'edit&id='.$id:'create'));}}master_redirect('admin_tahun.php');}
$q = App\Database\PageQuery::term($_GET['q'] ?? '');
$page = max(1, (int) ($_GET['page'] ?? 1));
$result=$service->yearsPage($q,$page);$rows=$result['rows'];
$page = $result['page'];
$selected=isset($_GET['id'])?$service->year((int)$_GET['id']):null;$mode=(string)($_GET['action']??'');master_header('Tahun Ajaran', ['show_heading' => false]);
?>
<div class="ah-page-head"><div><h1 class="h3">Tahun Ajaran</h1><p class="text-muted mb-0">Sistem menjaga agar paling banyak dan melalui UI tepat satu semester aktif.</p></div><a class="btn btn-success align-self-center" href="?action=create">Tambah Semester</a></div>
<?php if($mode==='create'||($mode==='edit'&&$selected)):$r=array_replace($selected??[], $_SESSION['_tahun_old']??[]); ?><div class="card border-0 shadow-sm mb-4"><div class="card-body"><form method="post" class="row g-3"><?= master_csrf() ?><input type="hidden" name="action" value="save"><?php if($selected): ?><input type="hidden" name="id" value="<?= (int)$selected['id'] ?>"><?php endif; ?><div class="col-md-4"><label class="form-label" for="tahun">Tahun (YYYY/YYYY)</label><input class="form-control" id="tahun" name="tahun" pattern="[0-9]{4}/[0-9]{4}" required value="<?= master_e($r['tahun']??'') ?>"><?= ah_field_error('tahun','_tahun_old') ?></div><div class="col-md-4"><label class="form-label" for="semester">Semester</label><select class="form-select" id="semester" name="semester"><option <?= ($r['semester']??'Ganjil')==='Ganjil'?'selected':'' ?>>Ganjil</option><option <?= ($r['semester']??'')==='Genap'?'selected':'' ?>>Genap</option></select><?= ah_field_error('semester','_tahun_old') ?></div><div class="col-md-4 d-flex align-items-end"><button class="btn btn-success">Simpan</button>&nbsp;<a class="btn btn-light" href="admin_tahun.php">Batal</a></div></form></div></div><?php endif; ?>
<?php ah_list_search($q, 'Cari tahun, semester, atau status'); ?>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th scope="col">ID</th><th scope="col">Tahun</th><th scope="col">Semester</th><th scope="col">Status</th><th scope="col">Aksi</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr class="<?= $r['status']==='Aktif'?'table-success':'' ?>"><td><?= (int)$r['id'] ?></td><td><?= master_e($r['tahun']) ?></td><td><?= master_e($r['semester']) ?></td><td><?= $r['archived_at']?'Arsip':$r['status'] ?></td><td><div class="d-flex gap-1"><a class="btn btn-sm btn-outline-warning" href="?action=edit&amp;id=<?= (int)$r['id'] ?>">Ubah</a><?php if($r['status']!=='Aktif'&&!$r['archived_at']): ?><form data-confirm="Ubah semester ini? Mengaktifkan semester mengganti cakupan semester aktif untuk kelas, jadwal, dan penugasan. Arsip hanya untuk semester nonaktif; riwayat lama tidak dihapus." method="post"><?= master_csrf() ?><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><button class="btn btn-sm btn-outline-success" name="action" value="activate">Aktifkan</button></form><form method="post" onsubmit="return confirm('Arsipkan semester nonaktif ini? Semester tidak lagi ditawarkan pada daftar aktif; kelas, absensi, dan riwayat lama tetap tersimpan.')"><?= master_csrf() ?><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><button class="btn btn-sm btn-outline-danger" name="action" value="archive">Arsipkan</button></form><?php elseif($r['archived_at']): ?><form data-confirm="Ubah semester ini? Mengaktifkan semester mengganti cakupan semester aktif untuk kelas, jadwal, dan penugasan. Arsip hanya untuk semester nonaktif; riwayat lama tidak dihapus." method="post"><?= master_csrf() ?><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><button class="btn btn-sm btn-outline-primary" name="action" value="restore">Pulihkan</button></form><?php endif; ?></div></td></tr><?php endforeach; ?><?php if ($rows === []): ?><tr><td colspan="5"><?= ah_empty('Tidak ada hasil', 'Ubah kata pencarian atau tambahkan data melalui tombol di atas.') ?></td></tr><?php endif; ?></tbody></table></div></div>
<?php master_pagination((int) $result['total'], $page, 20); ah_old_clear('_tahun_old');master_footer(); ?>
