<?php

declare(strict_types=1);

use App\MasterData\MasterDataException;
require_once __DIR__ . '/_guard.php';
require_once __DIR__ . '/_master_ui.php';
$service=master_data_service();
if($_SERVER['REQUEST_METHOD']==='POST'){try{$action=(string)($_POST['action']??'');$id=(int)($_POST['id']??0);if($action==='save'){$service->saveClass($_POST,$id?:null);master_flash('success','Kelas berhasil disimpan.');}elseif($action==='assign'){$service->assignActiveClass($_POST,(int)$currentUser['id']);master_flash('success','Santri ditempatkan ke kelas pada semester aktif; riwayat lama tetap tersimpan.');}else{$service->setClassState($id,$action);master_flash('success','Status kelas berhasil diperbarui.');}}catch(MasterDataException $e){master_flash('danger',$e->getMessage());if($action==='save'){ah_validation_keep($_POST,['nama_kelas', 'jenjang'],$e,'_kelas_old');master_redirect('admin_kelas.php?action='.($id?'edit&id='.$id:'create'));}if($action==='assign'){ah_validation_keep($_POST,['santri_id','kelas_id','tanggal_mulai'],$e,'_kelas_assign');}}master_redirect('admin_kelas.php');}
$q = App\Database\PageQuery::term($_GET['q'] ?? '');
$page = max(1, (int) ($_GET['page'] ?? 1));
$result=$service->classesPage($q,$page);$rows=$result['rows'];
$page = $result['page'];
$selected=isset($_GET['id'])?$service->class((int)$_GET['id']):null;$mode=(string)($_GET['action']??'');$activeYear=null;foreach($service->years() as $year){if($year['status']==='Aktif'&&!$year['archived_at']){$activeYear=$year;break;}}master_header('Kelas dan Keanggotaan', ['show_heading' => false]);
?>
<div class="ah-page-head"><div><h1 class="h3">Kelas dan Keanggotaan</h1><p class="text-muted mb-0">Semester aktif: <?= $activeYear?master_e($activeYear['tahun'].' '.$activeYear['semester']):'belum diatur' ?>.</p></div><a class="btn btn-success align-self-center" href="?action=create">Tambah Kelas</a></div>
<?php if($mode==='create'||($mode==='edit'&&$selected)):$r=array_replace($selected??[], $_SESSION['_kelas_old']??[]); ?><div class="card border-0 shadow-sm mb-4"><div class="card-header bg-white"><strong><?= $selected?'Ubah Kelas':'Tambah Kelas' ?></strong></div><div class="card-body"><form method="post" class="row g-3"><?= master_csrf() ?><input type="hidden" name="action" value="save"><?php if($selected): ?><input type="hidden" name="id" value="<?= (int)$selected['id'] ?>"><?php endif; ?><div class="col-md-5"><label class="form-label" for="nama_kelas">Nama kelas</label><input class="form-control" id="nama_kelas" name="nama_kelas" required value="<?= master_e($r['nama_kelas']??'') ?>"><?= ah_field_error('nama_kelas','_kelas_old') ?></div><div class="col-md-5"><label class="form-label" for="jenjang">Jenjang</label><input class="form-control" id="jenjang" name="jenjang" required value="<?= master_e($r['jenjang']??'') ?>"><?= ah_field_error('jenjang','_kelas_old') ?></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-success">Simpan</button></div></form></div></div><?php endif; ?>
<div class="card border-0 shadow-sm mb-4"><div class="card-header bg-white"><strong>Tempatkan Santri pada Semester Aktif</strong></div><div class="card-body"><?php if($activeYear): ?><form data-confirm="Tempatkan santri pada kelas ini di semester aktif? Keanggotaan aktif berubah; riwayat kelas dan snapshot pertemuan lama tetap tersimpan." method="post" class="row g-3"><?= master_csrf() ?><input type="hidden" name="action" value="assign"><div class="col-md-5"><label class="form-label" for="santri_id">Santri</label><select class="form-select" id="santri_id" name="santri_id" required><option value="">Pilih santri</option><?php foreach($service->santriOptions() as $s): ?><option value="<?= (int)$s['id'] ?>" <?= ah_old('santri_id',null,'_kelas_assign') === (string)$s['id'] ? 'selected' : '' ?>><?= master_e($s['nis'].' — '.$s['nama_santri']) ?></option><?php endforeach; ?></select><?= ah_field_error('santri_id','_kelas_assign') ?></div><div class="col-md-3"><label class="form-label" for="kelas_id">Kelas</label><select class="form-select" id="kelas_id" name="kelas_id" required><?php foreach($service->classes() as $r):if($r['archived_at']||(int)$r['is_active']!==1)continue; ?><option value="<?= (int)$r['id'] ?>" <?= ah_old('kelas_id',null,'_kelas_assign') === (string)$r['id'] ? 'selected' : '' ?>><?= master_e($r['nama_kelas']) ?></option><?php endforeach; ?></select><?= ah_field_error('kelas_id','_kelas_assign') ?></div><div class="col-md-2"><label class="form-label" for="tanggal_mulai">Tanggal mulai</label><input class="form-control" type="date" id="tanggal_mulai" name="tanggal_mulai" value="<?= ah_e(ah_old('tanggal_mulai',['tanggal_mulai'=>date('Y-m-d')],'_kelas_assign')) ?>" required><?= ah_field_error('tanggal_mulai','_kelas_assign') ?></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary">Tempatkan</button></div></form><?php else: ?><div class="alert alert-warning mb-0">Aktifkan satu tahun ajaran terlebih dahulu.</div><?php endif; ?></div></div>
<?php ah_list_search($q, 'Cari nama kelas atau jenjang'); ?>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th scope="col">ID</th><th scope="col">Nama kelas</th><th scope="col">Jenjang</th><th scope="col">Status</th><th scope="col">Aksi</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?= (int)$r['id'] ?></td><td><?= master_e($r['nama_kelas']) ?></td><td><?= master_e($r['jenjang']) ?></td><td><?= $r['archived_at']?'Arsip':((int)$r['is_active']===1?'Aktif':'Nonaktif') ?></td><td><div class="d-flex gap-1"><a class="btn btn-sm btn-outline-warning" href="?action=edit&amp;id=<?= (int)$r['id'] ?>">Ubah</a><form data-confirm="Ubah status kelas ini? Kelas nonaktif atau arsip tidak dapat dipilih untuk penugasan baru. Riwayat keanggotaan dan absensi lama tetap tersimpan." method="post"><?= master_csrf() ?><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><button class="btn btn-sm btn-outline-secondary" name="action" value="<?= (int)$r['is_active']===1?'deactivate':'activate' ?>"><?= (int)$r['is_active']===1?'Nonaktifkan':'Aktifkan' ?></button></form><form data-confirm="Ubah status kelas ini? Kelas nonaktif atau arsip tidak dapat dipilih untuk penugasan baru. Riwayat keanggotaan dan absensi lama tetap tersimpan." method="post"><?= master_csrf() ?><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><button class="btn btn-sm btn-outline-danger" name="action" value="<?= $r['archived_at']?'restore':'archive' ?>"><?= $r['archived_at']?'Pulihkan':'Arsipkan' ?></button></form></div></td></tr><?php endforeach; ?><?php if ($rows === []): ?><tr><td colspan="5"><?= ah_empty('Tidak ada hasil', 'Ubah kata pencarian atau tambahkan data melalui tombol di atas.') ?></td></tr><?php endif; ?></tbody></table></div></div>
<?php master_pagination((int) $result['total'], $page, 20); ah_old_clear('_kelas_old');ah_old_clear('_kelas_assign');master_footer(); ?>
