<?php

declare(strict_types=1);

use App\Http\Csrf;
use App\Ui\Denial;
use App\V3\V3Exception;

require_once dirname(__DIR__).'/app/bootstrap.php';
$currentUser=authorization()->requireWebUser();$caps=capabilities()->v3Capabilities($currentUser);
if(array_intersect(['v3.konseling.kelola','v3.binaan.baca','v3.pengawasan','v3.koreksi'],array_keys($caps))===[]){Denial::render('Akun ini tidak memiliki akses konseling V3.','Akses mengikuti penugasan aktif atau hak pengawasan admin.');}
$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT);if(!$id)Denial::render('Kasus tidak ditemukan.','ID kasus tidak valid.');
$service=v3_konseling_service();$error='';
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    try{
        Csrf::requireValid($_POST['_csrf']??$_SERVER['HTTP_X_CSRF_TOKEN']??null);$action=(string)($_POST['aksi']??'');$result=null;
        if($action==='koreksi_kasus')$result=$service->correctCase($currentUser,(int)$id,$_POST);
        elseif($action==='status_kasus')$result=$service->transitionCase($currentUser,(int)$id,$_POST);
        elseif($action==='tambah_tautan')$result=$service->addLinks($currentUser,(int)$id,$_POST);
        elseif($action==='buat_sesi')$result=$service->createSession($currentUser,(int)$id,$_POST);
        elseif($action==='status_sesi')$result=$service->transitionSession($currentUser,(int)($_POST['sesi_id']??0),$_POST);
        elseif($action==='koreksi_sesi')$result=$service->correctSession($currentUser,(int)($_POST['sesi_id']??0),$_POST);
        elseif($action==='diketahui_kasus')$result=$service->acknowledge($currentUser,'kasus',(int)$id,$_POST);
        elseif($action==='diketahui_sesi')$result=$service->acknowledge($currentUser,'sesi',(int)($_POST['sesi_id']??0),$_POST);
        else throw new V3Exception('Aksi tidak dikenal.');
        ah_flash_set('success',$result['replayed']?'Permintaan identik sudah pernah diproses.':'Perubahan konseling tersimpan bersama audit.');ah_redirect('/portal/v3_konseling_detail.php?id='.(int)$id);
    }catch(V3Exception $exception){$error=$exception->getMessage();}
}
try{$detail=$service->show($currentUser,(int)$id);$timeline=$service->timeline($currentUser,(int)$id);}catch(V3Exception $exception){Denial::render('Kasus tidak ditemukan atau tidak dapat diakses.',$exception->getMessage());}
$case=$detail['kasus'];$canManage=isset($caps['v3.konseling.kelola'])&&capabilities()->v3AppliesToSantri($currentUser,'v3.konseling.kelola',$case['santri_id'],$case['tahun_ajaran_id']);$canCorrect=$canManage||isset($caps['v3.koreksi']);$canAck=isset($caps['v3.murobi.mengetahui'])&&capabilities()->v3AppliesToSantri($currentUser,'v3.murobi.mengetahui',$case['santri_id'],$case['tahun_ajaran_id']);$open=!in_array($case['status'],['Selesai','Dibatalkan'],true);$options=$canManage?$service->options($currentUser,$case['santri_id'],$case['tahun_ajaran_id']):['pelanggaran'=>[]];$key=static fn(string $action):string=>'web-'.$action.'-'.bin2hex(random_bytes(12));
ah_page_open(['title'=>'Detail konseling','heading'=>'Detail kasus konseling','description'=>'Kasus, tautan, sesi, revisi, dan catatan murobi dipertahankan sebagai riwayat.','user'=>$currentUser,'active'=>'v3.konseling','breadcrumbs'=>[['label'=>'Beranda','url'=>app_url('/portal/index.php')],['label'=>'Konseling','url'=>app_url('/portal/v3_konseling.php')],['label'=>'Detail']]]);if($error!=='')ah_note('danger',$error);
?>
<section class="ah-card mb-4"><div class="ah-card__body"><div class="d-flex flex-wrap justify-content-between gap-2"><div><h2 class="h4 mb-1"><?= ah_e($case['santri_nama']) ?></h2><p class="text-muted mb-0"><?= ah_e($case['tahun'].' / '.$case['semester'].' · dibuka '.$case['dibuka_pada']) ?></p></div><span class="badge text-bg-secondary align-self-start"><?= ah_e($case['status']) ?></span></div><hr><dl class="row"><dt class="col-sm-3">Kerahasiaan</dt><dd class="col-sm-9"><?= ah_e($case['kerahasiaan']) ?></dd><?php if($detail['akses_internal']): ?><dt class="col-sm-3">Tujuan</dt><dd class="col-sm-9" style="white-space:pre-wrap"><?= ah_e($case['tujuan']) ?></dd><dt class="col-sm-3">Ringkasan penutupan</dt><dd class="col-sm-9" style="white-space:pre-wrap"><?= ah_e($case['ringkasan_penutupan']??'—') ?></dd><?php endif ?><dt class="col-sm-3">Versi</dt><dd class="col-sm-9"><?= (int)$case['version'] ?></dd></dl><a class="btn btn-outline-secondary" href="<?= ah_e(app_url('/portal/v3_konseling_cetak.php?id='.(int)$id)) ?>" target="_blank" rel="noopener">Cetak sesuai hak akses</a></div></section>
<div class="row g-4 mb-4"><div class="col-12 col-lg-6"><section class="ah-card h-100"><div class="ah-card__body"><h2 class="h5">Pelanggaran terhubung</h2><?php if($detail['tautan']===[]): ?><?= ah_empty('Tidak ada tautan','Kasus ini berdiri sendiri.') ?><?php else: ?><ul><?php foreach($detail['tautan'] as $link): ?><li><a href="<?= ah_e(app_url('/portal/v3_pelanggaran_detail.php?id='.(int)$link['pelanggaran_id'])) ?>">Pelanggaran #<?= (int)$link['pelanggaran_id'] ?></a> · <?= ah_e($link['kategori'].' · '.$link['status']) ?><?= $link['sesi_id']?' · sesi #'.(int)$link['sesi_id']:'' ?></li><?php endforeach ?></ul><?php endif ?></div></section></div><div class="col-12 col-lg-6"><section class="ah-card h-100"><div class="ah-card__body"><h2 class="h5">Rekomendasi yang ditindaklanjuti</h2><?php if($detail['rekomendasi']===[]): ?><p class="text-muted">Tidak ada rekomendasi tertaut.</p><?php else: ?><ul><?php foreach($detail['rekomendasi'] as $recommendation): ?><li><strong><?= ah_e($recommendation['label']) ?></strong> · <?= (int)$recommendation['total_poin'] ?> poin</li><?php endforeach ?></ul><?php endif ?></div></section></div></div>
<section class="ah-card mb-4"><div class="ah-card__body"><h2 class="h5">Timeline</h2><ol><?php foreach($timeline['rows'] as $event): ?><li><?= ah_e($event['waktu'].' · '.$event['jenis']) ?></li><?php endforeach ?></ol></div></section>
<section class="ah-card mb-4"><div class="ah-card__body"><h2 class="h5">Sesi konseling</h2><?php if($detail['sesi']===[]): ?><?= ah_empty('Belum ada sesi','Jadwalkan sesi pertama untuk memulai pendampingan.') ?><?php else: ?><?php foreach($detail['sesi'] as $session): ?><article class="border rounded p-3 mb-3<?= $session['digantikan_oleh_id']?' opacity-75':'' ?>"><div class="d-flex justify-content-between gap-2"><strong>Sesi #<?= (int)$session['id'] ?> · <?= ah_e($session['jadwal']) ?></strong><span class="badge text-bg-light"><?= ah_e($session['status']) ?></span></div><?php if($detail['akses_internal']): ?><p class="mb-1 mt-2"><strong>Ringkasan internal:</strong> <?= ah_e($session['ringkasan_internal']??'—') ?></p><p class="mb-1"><strong>Hasil:</strong> <?= ah_e($session['hasil']??'—') ?></p><p class="mb-1"><strong>Tindak lanjut:</strong> <?= ah_e($session['tindak_lanjut']??'—') ?></p><?php endif ?><?php if($session['digantikan_oleh_id']): ?><small class="text-muted">Direvisi menjadi sesi #<?= (int)$session['digantikan_oleh_id'] ?>.</small><?php endif ?>
<?php if($canManage&&$session['digantikan_oleh_id']===null&&in_array($session['status'],['Dijadwalkan','Dijadwalkan Ulang'],true)): ?><form method="post" class="row g-2 mt-2"><?= ah_csrf() ?><input type="hidden" name="aksi" value="status_sesi"><input type="hidden" name="sesi_id" value="<?= (int)$session['id'] ?>"><input type="hidden" name="version" value="<?= (int)$session['version'] ?>"><input type="hidden" name="idempotency_key" value="<?= ah_e($key('session-status')) ?>"><div class="col-12 col-md-4"><label class="form-label">Status baru</label><select class="form-select" name="status"><option>Selesai</option><option>Tidak Hadir</option><option>Dijadwalkan Ulang</option><option>Dibatalkan</option></select></div><div class="col-12 col-md-4"><label class="form-label">Realisasi / jadwal baru</label><input class="form-control" type="datetime-local" name="realisasi" value="<?= ah_e(date('Y-m-d\TH:i')) ?>"><input class="form-control mt-2" type="datetime-local" name="jadwal" value="<?= ah_e(str_replace(' ','T',substr($session['jadwal'],0,16))) ?>"></div><div class="col-12 col-md-4"><label class="form-label">Alasan bila jadwal ulang/batal</label><textarea class="form-control" name="alasan"></textarea></div><div class="col-12"><label class="form-label">Ringkasan internal saat selesai</label><textarea class="form-control" name="ringkasan_internal"></textarea><label class="form-label mt-2">Hasil saat selesai</label><textarea class="form-control" name="hasil"></textarea><label class="form-label mt-2">Tindak lanjut</label><textarea class="form-control" name="tindak_lanjut"></textarea><button class="btn btn-outline-primary mt-2">Simpan status sesi</button></div></form><?php endif ?>
<?php if($canCorrect&&$detail['akses_internal']&&$session['digantikan_oleh_id']===null): ?><details class="mt-3"><summary>Koreksi sesi dengan revisi</summary><form method="post" class="row g-2 mt-2"><?= ah_csrf() ?><input type="hidden" name="aksi" value="koreksi_sesi"><input type="hidden" name="sesi_id" value="<?= (int)$session['id'] ?>"><input type="hidden" name="version" value="<?= (int)$session['version'] ?>"><input type="hidden" name="idempotency_key" value="<?= ah_e($key('session-correct')) ?>"><div class="col-12 col-md-6"><label class="form-label">Jadwal</label><input class="form-control" type="datetime-local" name="jadwal" value="<?= ah_e(str_replace(' ','T',substr($session['jadwal'],0,16))) ?>" required></div><div class="col-12 col-md-6"><label class="form-label">Alasan koreksi</label><input class="form-control" name="alasan" required></div><div class="col-12"><label class="form-label">Ringkasan internal</label><textarea class="form-control" name="ringkasan_internal"><?= ah_e($session['ringkasan_internal']??'') ?></textarea><label class="form-label mt-2">Hasil</label><textarea class="form-control" name="hasil"><?= ah_e($session['hasil']??'') ?></textarea><label class="form-label mt-2">Tindak lanjut</label><textarea class="form-control" name="tindak_lanjut"><?= ah_e($session['tindak_lanjut']??'') ?></textarea><button class="btn btn-outline-secondary mt-2">Buat revisi sesi</button></div></form></details><?php endif ?>
<?php if($canAck&&$session['digantikan_oleh_id']===null): ?><form method="post" class="mt-3"><?= ah_csrf() ?><input type="hidden" name="aksi" value="diketahui_sesi"><input type="hidden" name="sesi_id" value="<?= (int)$session['id'] ?>"><input type="hidden" name="idempotency_key" value="<?= ah_e($key('ack-session')) ?>"><label class="form-label">Catatan murobi untuk sesi</label><textarea class="form-control" name="catatan" maxlength="2000"></textarea><button class="btn btn-outline-primary mt-2">Tandai mengetahui sesi</button></form><?php endif ?></article><?php endforeach ?><?php endif ?></div></section>
<?php if($canManage&&$open): ?><section class="ah-card mb-4"><div class="ah-card__body"><h2 class="h5">Jadwalkan sesi baru</h2><form method="post" class="row g-3"><?= ah_csrf() ?><input type="hidden" name="aksi" value="buat_sesi"><input type="hidden" name="idempotency_key" value="<?= ah_e($key('session-create')) ?>"><div class="col-12 col-md-6"><label class="form-label">Jadwal</label><input class="form-control" type="datetime-local" name="jadwal" value="<?= ah_e(date('Y-m-d\TH:i',time()+86400)) ?>" required></div><div class="col-12 col-md-6"><label class="form-label">Jadwal berikutnya (opsional)</label><input class="form-control" type="datetime-local" name="jadwal_berikut"></div><div class="col-12"><label class="form-label">Rencana tindak lanjut (opsional)</label><textarea class="form-control" name="tindak_lanjut" maxlength="5000"></textarea></div><?php foreach($options['pelanggaran'] as $violation): ?><div class="col-12 col-lg-6"><label class="border rounded p-2 d-block"><input class="form-check-input me-2" type="checkbox" name="pelanggaran_ids[]" value="<?= (int)$violation['id'] ?>">Tautkan #<?= (int)$violation['id'] ?> · <?= ah_e($violation['kategori']) ?></label></div><?php endforeach ?><div class="col-12"><button class="btn btn-primary">Simpan sesi</button></div></form></div></section><?php endif ?>
<?php if($canCorrect&&$detail['akses_internal']&&$open): ?><section class="ah-card mb-4"><div class="ah-card__body"><h2 class="h5">Koreksi kasus</h2><form method="post" class="row g-3"><?= ah_csrf() ?><input type="hidden" name="aksi" value="koreksi_kasus"><input type="hidden" name="version" value="<?= (int)$case['version'] ?>"><input type="hidden" name="idempotency_key" value="<?= ah_e($key('case-correct')) ?>"><div class="col-12"><label class="form-label">Tujuan</label><textarea class="form-control" name="tujuan" required><?= ah_e($case['tujuan']) ?></textarea></div><div class="col-12 col-md-4"><label class="form-label">Kerahasiaan</label><select class="form-select" name="kerahasiaan"><option <?= $case['kerahasiaan']==='Internal'?'selected':'' ?>>Internal</option><option <?= $case['kerahasiaan']==='Rahasia'?'selected':'' ?>>Rahasia</option></select></div><div class="col-12 col-md-8"><label class="form-label">Alasan koreksi</label><input class="form-control" name="alasan" required></div><div class="col-12"><button class="btn btn-outline-secondary">Simpan koreksi</button></div></form></div></section><?php endif ?>
<?php if($canManage&&$open): ?><section class="ah-card mb-4"><div class="ah-card__body"><h2 class="h5">Status kasus</h2><form method="post" class="row g-3"><?= ah_csrf() ?><input type="hidden" name="aksi" value="status_kasus"><input type="hidden" name="version" value="<?= (int)$case['version'] ?>"><input type="hidden" name="idempotency_key" value="<?= ah_e($key('case-status')) ?>"><div class="col-12 col-md-4"><label class="form-label">Status baru</label><select class="form-select" name="status"><?php if($case['status']==='Dibuka'): ?><option>Dalam Pendampingan</option><?php endif ?><option>Selesai</option><option>Dibatalkan</option></select></div><div class="col-12 col-md-8"><label class="form-label">Ringkasan penutupan (wajib untuk selesai)</label><textarea class="form-control" name="ringkasan_penutupan"></textarea><label class="form-label mt-2">Alasan pembatalan</label><textarea class="form-control" name="alasan"></textarea></div><div class="col-12"><button class="btn btn-outline-primary">Ubah status</button></div></form></div></section><?php endif ?>
<?php if($canAck): ?><section class="ah-card mb-4"><div class="ah-card__body"><h2 class="h5">Tanda mengetahui murobi</h2><form method="post"><?= ah_csrf() ?><input type="hidden" name="aksi" value="diketahui_kasus"><input type="hidden" name="idempotency_key" value="<?= ah_e($key('ack-case')) ?>"><label class="form-label">Catatan murobi (terpisah dari catatan internal)</label><textarea class="form-control" name="catatan" maxlength="2000"></textarea><button class="btn btn-outline-primary mt-2">Tandai mengetahui kasus</button></form></div></section><?php endif ?>
<section class="ah-card"><div class="ah-card__body"><h2 class="h5">Riwayat catatan murobi</h2><?php if($detail['catatan_murobi']===[]): ?><p class="text-muted">Belum ada.</p><?php else: ?><ul><?php foreach($detail['catatan_murobi'] as $note): ?><li><?= ah_e($note['diketahui_pada']) ?> · <?= $note['sesi_id']?'sesi #'.(int)$note['sesi_id']:'kasus' ?><?= $note['catatan']?' — '.ah_e($note['catatan']):'' ?></li><?php endforeach ?></ul><?php endif ?></div></section>
<?php ah_page_close(); ?>
