<?php

declare(strict_types=1);

use App\Http\Csrf;
use App\Ui\Denial;
use App\V3\AttachmentStorage;
use App\V3\V3Exception;

require_once dirname(__DIR__).'/app/bootstrap.php';
$currentUser=authorization()->requireWebUser();$caps=capabilities()->v3Capabilities($currentUser);
if(array_intersect(['v3.pelanggaran.kelola','v3.binaan.baca','v3.pengawasan','v3.koreksi'],array_keys($caps))===[]){Denial::render('Akun ini tidak memiliki akses pelanggaran V3.','Akses mengikuti penugasan aktif atau hak pengawasan admin.');}
$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT);if(!$id){Denial::render('Catatan tidak ditemukan.','ID pelanggaran tidak valid.');}
$service=v3_pelanggaran_service();$error='';
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    try{
        Csrf::requireValid($_POST['_csrf']??$_SERVER['HTTP_X_CSRF_TOKEN']??null);$action=(string)($_POST['aksi']??'');
        if($action==='koreksi'){$storage=new AttachmentStorage(APP_ROOT.'/storage/private/v3');$file=$storage->stageUpload($_FILES['lampiran']??null);$result=$service->correct($currentUser,(int)$id,$_POST,$file);$target=(int)$result['data']['pelanggaran']['id'];}
        elseif($action==='batal'){$result=$service->cancel($currentUser,(int)$id,$_POST);$target=(int)$id;}
        elseif($action==='diketahui'){$result=$service->acknowledge($currentUser,(int)$id,$_POST);$target=(int)$id;}
        else{throw new V3Exception('Aksi tidak dikenal.');}
        ah_flash_set('success',$result['replayed']?'Permintaan identik sudah diproses.':'Perubahan tersimpan dengan audit dan riwayat.');ah_redirect('/portal/v3_pelanggaran_detail.php?id='.$target);
    }catch(V3Exception $exception){$error=$exception->getMessage();}
}
try{$detail=$service->show($currentUser,(int)$id);}catch(V3Exception $exception){Denial::render('Catatan tidak ditemukan atau tidak dapat diakses.',$exception->getMessage());}
$row=$detail['pelanggaran'];$current=$row['digantikan_oleh_id']===null;$canManage=isset($caps['v3.pelanggaran.kelola'])||isset($caps['v3.koreksi']);
$canAcknowledge=isset($caps['v3.murobi.mengetahui'])&&capabilities()->v3AppliesToSantri($currentUser,'v3.murobi.mengetahui',$row['santri_id'],$row['tahun_ajaran_id']);
$key=static fn(string $action):string=>'web-'.$action.'-'.bin2hex(random_bytes(12));
ah_page_open(['title'=>'Detail pelanggaran','heading'=>'Detail pelanggaran V3','description'=>'Ledger, revisi, rekomendasi, dan tanda mengetahui dipertahankan sebagai riwayat.','user'=>$currentUser,'active'=>'v3.pelanggaran','breadcrumbs'=>[['label'=>'Beranda','url'=>app_url('/portal/index.php')],['label'=>'Pelanggaran','url'=>app_url('/portal/v3_pelanggaran.php')],['label'=>'Detail']]]);
if($error!=='')ah_note('danger',$error);foreach($detail['peringatan_konfigurasi'] as $warning)ah_note('warning',$warning);
?>
<section class="ah-card mb-4"><div class="ah-card__body"><div class="d-flex flex-wrap justify-content-between gap-2"><div><h2 class="h4 mb-1"><?= ah_e($row['santri_nama']) ?></h2><p class="text-muted mb-0"><?= ah_e($row['tahun'].' / '.$row['semester'].' · '.$row['waktu_kejadian']) ?></p></div><span class="badge text-bg-secondary align-self-start"><?= ah_e($row['status']) ?></span></div><hr>
<dl class="row"><dt class="col-sm-3">Kategori</dt><dd class="col-sm-9"><?= ah_e($row['kategori'].' · '.$row['tingkat']) ?></dd><dt class="col-sm-3">Poin snapshot</dt><dd class="col-sm-9"><?= (int)$row['poin'] ?></dd><dt class="col-sm-3">Tempat</dt><dd class="col-sm-9"><?= ah_e($row['tempat']??'—') ?></dd><dt class="col-sm-3">Uraian</dt><dd class="col-sm-9" style="white-space:pre-wrap"><?= ah_e($row['uraian']) ?></dd><dt class="col-sm-3">Saksi</dt><dd class="col-sm-9" style="white-space:pre-wrap"><?= ah_e($row['saksi']??'—') ?></dd><dt class="col-sm-3">Versi</dt><dd class="col-sm-9"><?= (int)$row['version'] ?></dd></dl>
<?php if($row['digantikan_oleh_id']!==null): ?><p class="alert alert-info">Catatan ini sudah dikoreksi. <a href="?id=<?= (int)$row['digantikan_oleh_id'] ?>">Buka revisi berikutnya</a>.</p><?php endif ?>
</div></section>
<div class="row g-4 mb-4"><div class="col-12 col-lg-6"><section class="ah-card h-100"><div class="ah-card__body"><h2 class="h5">Poin & rekonsiliasi</h2><p class="display-6"><?= (int)$detail['total_poin'] ?> poin</p><p class="text-muted">Agregat <?= (int)$detail['rekonsiliasi']['agregat'] ?> · ledger <?= (int)$detail['rekonsiliasi']['ledger'] ?> · selisih <?= (int)$detail['rekonsiliasi']['selisih'] ?></p><ul><?php foreach($detail['ledger'] as $ledger): ?><li><?= ah_e($ledger['created_at'].' · '.($ledger['perubahan_poin']>=0?'+':'').$ledger['perubahan_poin'].' · '.$ledger['alasan']) ?><?= $ledger['pembalik_dari_id']?' (pembalik #'.(int)$ledger['pembalik_dari_id'].')':'' ?></li><?php endforeach ?></ul></div></section></div><div class="col-12 col-lg-6"><section class="ah-card h-100"><div class="ah-card__body"><h2 class="h5">Rekomendasi manual</h2><?php if($detail['rekomendasi']===[]): ?><?= ah_empty('Belum ada rekomendasi','Sistem tidak membuat hukuman, konseling, atau perubahan akademik otomatis.') ?><?php else: foreach($detail['rekomendasi'] as $recommendation): ?><div class="border rounded p-3 mb-2"><strong><?= ah_e($recommendation['label']) ?></strong><p class="mb-0"><?= ah_e($recommendation['rekomendasi']) ?></p><small class="text-muted">Status <?= ah_e($recommendation['status']) ?> · snapshot total <?= (int)$recommendation['total_poin'] ?></small></div><?php endforeach; endif ?></div></section></div></div>
<section class="ah-card mb-4"><div class="ah-card__body"><h2 class="h5">Lampiran privat</h2><?php if($detail['lampiran']===[]): ?><p class="text-muted">Tidak ada lampiran.</p><?php else: ?><ul><?php foreach($detail['lampiran'] as $file): ?><li><a href="<?= ah_e(app_url('/portal/v3_lampiran.php?id='.(int)$file['id'])) ?>"><?= ah_e($file['nama']) ?></a> · <?= ah_e($file['mime']) ?> · <?= number_format($file['ukuran']/1024,1) ?> KB</li><?php endforeach ?></ul><?php endif ?></div></section>
<?php if($current&&$canManage&&$row['status']!=='Dibatalkan'): ?><section class="ah-card mb-4"><div class="ah-card__body"><h2 class="h5">Koreksi beralasan</h2><p class="text-muted">Koreksi membuat revisi dan ledger baru; catatan ini tidak ditimpa.</p><form method="post" enctype="multipart/form-data" class="row g-3"><?= ah_csrf() ?><input type="hidden" name="aksi" value="koreksi"><input type="hidden" name="version" value="<?= (int)$row['version'] ?>"><input type="hidden" name="idempotency_key" value="<?= ah_e($key('correct')) ?>"><input type="hidden" name="katalog_id" value="<?= (int)$row['katalog_id'] ?>"><div class="col-12 col-md-6"><label class="form-label" for="corr-time">Waktu</label><input class="form-control" id="corr-time" type="datetime-local" name="waktu_kejadian" value="<?= ah_e(str_replace(' ','T',substr($row['waktu_kejadian'],0,16))) ?>" required></div><div class="col-12 col-md-6"><label class="form-label" for="corr-place">Tempat</label><input class="form-control" id="corr-place" name="tempat" maxlength="255" value="<?= ah_e($row['tempat']??'') ?>"></div><div class="col-12"><label class="form-label" for="corr-desc">Uraian</label><textarea class="form-control" id="corr-desc" name="uraian" maxlength="5000" required><?= ah_e($row['uraian']) ?></textarea></div><div class="col-12"><label class="form-label" for="corr-witness">Saksi</label><textarea class="form-control" id="corr-witness" name="saksi" maxlength="2000"><?= ah_e($row['saksi']??'') ?></textarea></div><?php if(isset($caps['v3.koreksi'])): ?><div class="col-12 col-md-4"><label class="form-label" for="corr-point">Poin koreksi admin</label><input class="form-control" id="corr-point" type="number" name="poin" min="0" max="2147483647" value="<?= (int)$row['poin'] ?>"></div><?php endif ?><div class="col-12"><label class="form-label" for="corr-reason">Alasan koreksi</label><textarea class="form-control" id="corr-reason" name="alasan" maxlength="1000" required></textarea></div><div class="col-12"><label class="form-label" for="corr-file">Bukti privat tambahan (opsional)</label><input class="form-control" id="corr-file" type="file" name="lampiran" accept="image/jpeg,image/png,application/pdf"></div><div class="col-12"><button class="btn btn-primary">Buat revisi</button></div></form><hr><form method="post" data-confirm="Batalkan pelanggaran dan buat pembalik poin?"><?= ah_csrf() ?><input type="hidden" name="aksi" value="batal"><input type="hidden" name="version" value="<?= (int)$row['version'] ?>"><input type="hidden" name="idempotency_key" value="<?= ah_e($key('cancel')) ?>"><label class="form-label" for="cancel-reason">Alasan pembatalan</label><textarea class="form-control" id="cancel-reason" name="alasan" maxlength="1000" required></textarea><button class="btn btn-outline-danger mt-2">Batalkan dengan pembalik poin</button></form></div></section><?php endif ?>
<?php if($canAcknowledge): ?><section class="ah-card mb-4"><div class="ah-card__body"><h2 class="h5">Tanda mengetahui murobi</h2><form method="post"><?= ah_csrf() ?><input type="hidden" name="aksi" value="diketahui"><input type="hidden" name="idempotency_key" value="<?= ah_e($key('ack')) ?>"><label class="form-label" for="murobi-note">Catatan murobi (opsional)</label><textarea class="form-control" id="murobi-note" name="catatan" maxlength="2000"></textarea><button class="btn btn-outline-primary mt-2">Tandai mengetahui</button></form></div></section><?php endif ?>
<section class="ah-card"><div class="ah-card__body"><h2 class="h5">Riwayat revisi</h2><ol><?php foreach($detail['riwayat_revisi'] as $revision): ?><li><a href="?id=<?= (int)$revision['id'] ?>">Catatan #<?= (int)$revision['id'] ?></a> · versi <?= (int)$revision['version'] ?> · <?= ah_e($revision['status']) ?><?php if($revision['alasan_revisi']): ?> — <?= ah_e($revision['alasan_revisi']) ?><?php endif ?></li><?php endforeach ?></ol><h3 class="h6">Tanda mengetahui</h3><?php if($detail['murobi']===[]): ?><p class="text-muted">Belum ada.</p><?php else: ?><ul><?php foreach($detail['murobi'] as $note): ?><li><?= ah_e($note['diketahui_pada']) ?><?= $note['catatan']?' — '.ah_e($note['catatan']):'' ?></li><?php endforeach ?></ul><?php endif ?></div></section>
<?php ah_page_close(); ?>
